### PR TITLE
Update tag names, stub out data structure.

### PR DESCRIPTION
**Pull request by WillNilges**
This is a data structure I was talking about during the meeting that I was working on. It's pretty barebones, but we need to decide how to deal with this data.

### CODE REVIEW

**Comment by dylan-thegreenone** [comment]
Is there a reason the gain is not part of the bluetooth data struct?  If each part of the detection is packaged together, generating the JSON from that is very simple since predicting the length of the string is just addition.  I already made  a function that creates the JSON when all of the values are provided separately, and it being all in a single struct is even easier

**Comment by WillNilges** [comment]
Gain? I wasn't aware there was a gain to acquire. You're not talking about RSSI? Can you drop a link to what you're talking about?

**Comment by dylan-thegreenone** [comment]
Nope, I'm just dumb and forgot what rssi was.  If that data is all we need I can make a Json generator based off that.

**Comment by WillNilges** [comment]
That's what we talked about on Monday. I think that'll be it. Are we doing JSON, or are we gonna make a bare protocol? I thought we were gonna do the latter. Might want to send Gerber a message.

**Comment by WillNilges** [comment]
god fucking dammit im a clown i didnt mean to do that

**Comment by WillNilges** [comment]
Wow I completely clowned myself. Well done.

**Pull request closed without merging**
